[project]
name = "telemetrysystem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=6.0.0",
    "marimo>=0.20.2",
    "pandas>=3.0.0",
    "pandoc>=2.4",
    "plotly>=6.5.2",
    "polars>=1.38.0",
    "pyzmq>=27.1.0",
    "ruff>=0.15.2",
]

[tool.marimo.save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = true

[tool.marimo.formatting]
line_length = 88

[tool.marimo.display]
default_width = "medium"
dataframes = "rich"

[tool.marimo.runtime]
auto_instantiate = true
on_cell_change = "autorun"

[tool.marimo.package_management]
manager = "uv"